version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=net-conf
      - POSTGRES_PASSWORD=dumb-password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: "host"
  net-conf:
    build: ./net-conf
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=net-conf
      - POSTGRES_USER=net-conf
      - POSTGRES_PASSWORD=dumb-password
    restart: always
    command: ./main
    ports:
      - "4000:4000"
    entrypoint: /main
    network_mode: "host"
  ryu:
    build: ./ryu-rest
    ports:
      - 6653:6653
      - 8080:8080
    expose:
      - 7777
    network_mode: "host"
volumes:
  db:
    driver: local